name: annealed-nce
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
- python>=3.7
- numpy
- pandas
- scipy
- matplotlib
- pytorch
- pytest
- pip
- tqdm
- statsmodels
- seaborn
- black
- ipython
- jupyterlab
- jupytext
- scikit-learn
- jupytext
- htop  # no more black bars in htop in tmux on remote cluster
- flake8
- pip:
  - pytest-cov 
